[changelog]
header = ""
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}
{% for commit in commits %}
- {{ commit.message | upper_first }}\
{% endfor %}
{% endfor %}
"""
trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_parsers = [
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Bug Fixes" },
  { message = "^perf", group = "Performance Improvements" },
  { message = "^revert", group = "Reverts" },
  { message = "^refactor", group = "Code Refactoring", skip = true },
  { message = "^docs", skip = true },
  { message = "^style", skip = true },
  { message = "^chore", skip = true },
  { message = "^test", skip = true },
  { message = "^build", skip = true },
  { message = "^ci", skip = true },
]
filter_commits = true
tag_pattern = "v[0-9].*"
topo_order = false
sort_commits = "newest"
