name: Bug Report
description: Something isn't working as expected
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Just describe what's wrong and show us how to reproduce it.

  - type: textarea
    id: description
    attributes:
      label: What's wrong?
      description: Describe the issue and what you expected to happen
      placeholder: |
        When I convert 42 to English, I get "forty two" but I expected "forty-two" with a hyphen.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: How to reproduce
      description: Share the code that triggers the bug
      placeholder: |
        import { EnglishConverter } from 'n2words'
        console.log(EnglishConverter(42))
      render: javascript
    validations:
      required: true

  - type: input
    id: language
    attributes:
      label: Which language?
      description: Which language converter has the issue?
      placeholder: "e.g., English, Spanish, Arabic"

  - type: input
    id: version
    attributes:
      label: n2words version (optional)
      description: If you know it, what version are you using?
      placeholder: "e.g., 2.0.0"

  - type: textarea
    id: additional
    attributes:
      label: Anything else?
      description: Environment, Node version, or other helpful details
      placeholder: "Using Node.js v20, happens in both browser and Node..."
