name: Bug Report
description: Something isn't working as expected
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this!

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: What did you expect vs what actually happened?
      placeholder: "I expected X but got Y instead..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Code to reproduce
      description: Minimal code that shows the problem
      placeholder: |
        import { EnglishConverter } from 'n2words'
        EnglishConverter(42)  // returns "..." but expected "..."
      render: javascript
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version (optional)
      placeholder: "e.g., 2.0.0 or 'latest'"

  - type: textarea
    id: additional
    attributes:
      label: Anything else? (optional)
      placeholder: "Node version, browser, etc."
