name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: version
    attributes:
      label: n2words Version
      description: What version of n2words are you using?
      placeholder: "2.0.0"
    validations:
      required: true

  - type: dropdown
    id: language
    attributes:
      label: Language
      description: Which language converter are you using?
      options:
        - English (en)
        - Spanish (es)
        - French (fr)
        - German (de)
        - Italian (it)
        - Portuguese (pt)
        - Russian (ru)
        - Arabic (ar)
        - Chinese - Simplified (zh-Hans)
        - Chinese - Traditional (zh-Hant)
        - Japanese (ja)
        - Korean (ko)
        - Other (please specify in description)
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where are you using n2words?
      multiple: true
      options:
        - Node.js
        - Browser (via CDN)
        - Browser (bundled)
        - TypeScript
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version (if applicable)
      description: Run `node --version`
      placeholder: "v20.11.0"

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: When converting the number 42...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Minimal Reproduction
      description: Provide code to reproduce the issue
      placeholder: |
        import { EnglishConverter } from 'n2words'
        console.log(EnglishConverter(42))
        // Expected: "forty-two"
        // Actual: "forty two" (incorrect)
      render: javascript
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Should output "forty-two"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Outputs "forty two" (missing hyphen)
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: This only happens with numbers ending in 2...

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
