name: Feature Request
description: Suggest an idea or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Got an idea? We'd love to hear it!

  - type: textarea
    id: description
    attributes:
      label: What would you like?
      description: Describe the feature or improvement
      placeholder: "It would be nice if..."
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example (optional)
      description: How would it work?
      placeholder: |
        import { toOrdinal } from 'n2words/en-US'
        toOrdinal(1)  // "first"
      render: javascript

  - type: textarea
    id: additional
    attributes:
      label: Anything else? (optional)
      placeholder: "Context, links, similar libraries..."
