name: Feature Request
description: Suggest an idea or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Got an idea? We'd love to hear it!

  - type: textarea
    id: description
    attributes:
      label: What would you like to see?
      description: Describe the feature and why it would be useful
      placeholder: |
        It would be great if n2words could convert numbers to ordinals (1st, 2nd, 3rd).
        This would be useful for formatting dates and rankings.
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: How should it work?
      description: Show an example of how you'd like to use it (optional but helpful!)
      placeholder: |
        EnglishConverter(1, { ordinal: true })
        // "first"
      render: javascript

  - type: input
    id: language-code
    attributes:
      label: For a new language?
      description: If requesting language support, what's the language code?
      placeholder: "e.g., pt-BR, hi, sw"

  - type: textarea
    id: additional
    attributes:
      label: Anything else?
      description: Additional context, links, examples
      placeholder: "Similar to how library X does it..."
